In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchsummary import summary
from tqdm import tqdm
import matplotlib.pyplot as plt

if torch.cuda.is_available():
    device="cuda"
else:
    device="cpu"
device

'cpu'

In [2]:
data = pd.read_csv('./structuralparameters-vs-capacities-4500mofs.csv', index_col=False, header=0)
data

,usablegc,usablevc,density,porosity,Largestporeradius,SSA,SPV,du,metalw,metala
0,0.2294,0.003505,1525,40,2.22,632,26,289000,19449,3704
1,0.1965,0.003082,1566,20,1.77,529,13,289000,19449,3704
2,1.3542,0.013027,949,300,5.70,3024,316,217000,24053,7143
3,0.3773,0.004750,1255,40,2.27,1002,32,233000,15330,2439
4,0.4118,0.005179,1253,40,2.41,1085,32,465000,15330,2439
...,...,...,...,...,...,...,...,...,...,...
4495,0.1575,0.002740,1737,100,2.20,572,58,473000,29160,2469
4496,0.1573,0.002793,1773,100,2.18,561,56,473000,29932,2469
4497,0.2423,0.003802,1565,40,2.24,539,26,321000,11644,3333
4498,0.5283,0.005848,1102,40,2.56,1639,36,217000,16467,1408
4499,0.5398,0.005896,1087,100,2.60,1588,92,217000,16467,1408

In [3]:
limites_tabla = pd.read_csv('./limits.csv', index_col=False, header=0)
limites_tabla

   Variable          Units       lowlimit  highlimit
0  usablegc           wt.%       0.000001       9.00
1  usablevc           kg/L       0.000001       0.05
2   density           kg/L       0.100000       5.00
3  porosity  dimensionless       0.001000       0.90
4        Ri      angstroms       1.000000      20.00
5       ssa          m^2/g     100.000000   10000.00
6  specific         cm^3/g       0.001000      10.00
7        du              - -150000.000000   35000.00
8    metalw              %    1800.000000   75000.00
9    metala              %     500.000000   35000.00

In [4]:
data.max()

usablegc             1.114050e+01
usablevc             2.388700e-02
density              3.990000e+03
porosity             8.800000e+02
Largestporeradius    3.582000e+01
SSA                  6.037000e+03
SPV                  6.282000e+03
du                   3.073000e+06
metalw               7.058500e+04
metala               3.333300e+04
dtype: float64